---
steam:
  username: impestilent
  password: Thisshitblowingme1
  install_path: F:\SteamLibrary\steamapps\common\assettocorsa
  executable_path: acServer.exe
  force_update: false
http:
  hostname: 0.0.0.0:8772
  session_key: RANDOMLY_GENERATE_THIS
  server_manager_base_URL: null
  session_store_type: cookie
  session_store_path: ""
  tls:
    enabled: false
    cert_path: ""
    key_path: ""
monitoring:
  enabled: true
store:
  type: boltdb
  path: server_manager.db
  shared_data_path: null
  scheduled_event_check_loop: 0s
accounts:
  admin_password_override: null
live_map:
  refresh_interval_ms: 500
server:
  audit_logging: true
  performance_mode: false
  dont_open_browser: true
  scan_content_folder_for_changes: true
  use_car_name_cache: true
  persist_mid_session_results: true
  plugins: null
championships:
  recaptcha:
    site_key: null
    secret_key: null
lua:
  enabled: true
